USE gestao_ensaio;

CREATE TABLE IF NOT EXISTS Configuracoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    webhook VARCHAR(500) NULL,
    telefone VARCHAR(20) NULL,
    nome VARCHAR(255) NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
