USE gestao_ensaio;

INSERT IGNORE INTO Instrumento (nome) VALUES
('Acordeon'),
('Barítono de Pisto'),
('Clarinete'),
('Clarinete Alto'),
('Clarinete Baixo'),
('Clarinete Contra Baixo'),
('Corne Inglês'),
('Cornet'),
('Euphonium'),
('Fagote'),
('Flauta'),
('Flauta Baixo'),
('Flauta Contralto'),
('Flugelhorn'),
('Melofone'),
('Oboé'),
('Oboé D\'amore'),
('Pocket'),
('Sax Horn'),
('Saxofone Alto'),
('Saxofone Baixo'),
('Saxofone Barítono'),
('Saxofone Sopraniro C'),
('Saxofone Sopraniro R'),
('Saxofone Soprano Cur'),
('Saxofone Soprano Ret'),
('Saxofone Tenor'),
('Trombone'),
('Trombonito'),
('Trompa'),
('Trompete'),
('Tuba'),
('Tuba Helicon'),
('Tuba Wagneriana'),
('Viola'),
('Violino'),
('Violino Contralto'),
('Violoncelo'),
('Órgão');
