USE gestao_ensaio;

-- Inserir instrumentos organizados por naipes
-- Cordas
INSERT IGNORE INTO Instrumento (nome, tenantId) VALUES
('VIOLINO', NULL),
('VIOLINO CONTRALTO', NULL),
('VIOLA', NULL),
('VIOLONCELO', NULL);

-- Madeiras
INSERT IGNORE INTO Instrumento (nome, tenantId) VALUES
('FLAUTA', NULL),
('FLAUTA CONTRALTO', NULL),
('FLAUTA BAIXO', NULL),
('CLARINETE', NULL),
('CLARINETE ALTO', NULL),
('CLARINETE BAIXO', NULL),
('CLARINETE CONTRA BAIXO', NULL),
('OBOÉ', NULL),
('OBOÉ D\'AMORE', NULL),
('CORNE INGLÊS', NULL),
('FAGOTE', NULL),
('SAXOFONE SOPRANINO C', NULL),
('SAXOFONE SOPRANINO R', NULL),
('SAXOFONE SOPRANO CUR', NULL),
('SAXOFONE SOPRANO RET', NULL),
('SAXOFONE ALTO', NULL),
('SAXOFONE TENOR', NULL),
('SAXOFONE BARÍTONO', NULL),
('SAXOFONE BAIXO', NULL);

-- Metais
INSERT IGNORE INTO Instrumento (nome, tenantId) VALUES
('POCKET', NULL),
('CORNET', NULL),
('TROMPETE', NULL),
('FLUGELHORN', NULL),
('TROMPA', NULL),
('TROMBONITO', NULL),
('BARÍTONO DE PISTO', NULL),
('MELOFONE', NULL),
('TROMBONE', NULL),
('SAX HORN', NULL),
('TUBA WAGNERIANA', NULL),
('EUPHONIUM', NULL),
('TUBA', NULL);

-- Teclas
INSERT IGNORE INTO Instrumento (nome, tenantId) VALUES
('ACORDEON', NULL),
('ORGANISTA', NULL);
